// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package repo

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one

INSERT INTO customer (customer_name, phone_number, email)
VALUES ($1, $2, $3)
RETURNING id, customer_name, phone_number, email, created_at
`

type CreateCustomerParams struct {
	CustomerName string `json:"customer_name"`
	PhoneNumber  string `json:"phone_number"`
	Email        string `json:"email"`
}


func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.CustomerName, arg.PhoneNumber, arg.Email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CustomerName,
		&i.PhoneNumber,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO "order" (customer_id, product_name, price)
VALUES ($1, $2, $3)
RETURNING  customer_id, product_name, price, order_date
`

type CreateOrderParams struct {
	CustomerID  string `json:"customer_id"`
	ProductName string `json:"product_name"`
	Price       string `json:"price"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.CustomerID, arg.ProductName, arg.Price)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProductName,
		&i.Price,
		&i.OrderDate,
	)
	return i, err
}
