// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package repo

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (thread_id, sender, content)
VALUES ($1, $2, $3)
RETURNING id, thread_id, sender, content, created_at
`

type CreateMessageParams struct {
	ThreadID string `json:"thread_id"`
	Sender   string `json:"sender"`
	Content  string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ThreadID, arg.Sender, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO thread (topic)
VALUES ($1)
RETURNING id, topic, message, created_at, updated_at
`

func (q *Queries) CreateThread(ctx context.Context, topic string) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, topic)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMeageByID = `-- name: DeleteMeageByID :exec
DELETE FROM message
WHERE id = $1
`

func (q *Queries) DeleteMeageByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMeageByID, id)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, thread_id, sender, content, created_at FROM message
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesByThread = `-- name: GetMessagesByThread :many
SELECT id, thread_id, sender, content, created_at FROM message
WHERE thread_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMessagesByThread(ctx context.Context, threadID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Sender,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByThreadPaginated = `-- name: GetMessagesByThreadPaginated :many
SELECT id, thread_id, sender, content, created_at FROM message
WHERE thread_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetMessagesByThreadPaginatedParams struct {
	ThreadID string `json:"thread_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) GetMessagesByThreadPaginated(ctx context.Context, arg GetMessagesByThreadPaginatedParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByThreadPaginated, arg.ThreadID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Sender,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalMessageCountByThread = `-- name: GetTotalMessageCountByThread :one
SELECT COUNT(*) FROM message 
WHERE thread_id = $1
`

func (q *Queries) GetTotalMessageCountByThread(ctx context.Context, threadID string) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalMessageCountByThread, threadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateMesageByID = `-- name: UpdateMesageByID :one
UPDATE message
SET sender=$2, content=$3
WHERE id = $1
RETURNING id, thread_id, sender, content, created_at
`

type UpdateMesageByIDParams struct {
	ID      string `json:"id"`
	Sender  string `json:"sender"`
	Content string `json:"content"`
}

func (q *Queries) UpdateMesageByID(ctx context.Context, arg UpdateMesageByIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMesageByID, arg.ID, arg.Sender, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
