// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID           string           `json:"id"`
	CustomerName string           `json:"customer_name"`
	PhoneNumber  string           `json:"phone_number"`
	Email        string           `json:"email"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID          string           `json:"id"`
	CustomerID  string           `json:"customer_id"`
	ProductName string           `json:"product_name"`
	Price       string           `json:"price"`
	OrderDate   pgtype.Timestamp `json:"order_date"`
}
