// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	// -- name: CreateMessage :one
	// INSERT INTO message (thread, sender, content)
	// VALUES ($1, $2, $3)
	// RETURNING *;
	// -- name: GetMessageByID :one
	// SELECT * FROM message
	// WHERE id = $1;
	// -- name: GetMessagesByThread :many
	// SELECT * FROM message
	// WHERE thread = $1
	// ORDER BY created_at DESC;
	// -- name: CustomerOrders :many
	// INSERT INTO orders (reference, phone_number, amount, transaction_status, transaction_description)
	// VALUES ($1, $2, $3, $4, $5)
	// RETURNING *;
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
