// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateThread(ctx context.Context, topic string) (Thread, error)
	DeleteMeageByID(ctx context.Context, id string) error
	GetMessageByID(ctx context.Context, id string) (Message, error)
	GetMessagesByThread(ctx context.Context, threadID string) ([]Message, error)
	UpdateMesageByID(ctx context.Context, arg UpdateMesageByIDParams) (Message, error)
}

var _ Querier = (*Queries)(nil)
